-- User roles mapping using enum app_role
drop table if exists public.user_roles cascade;
create table public.user_roles (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  role        public.app_role not null default 'user',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique(user_id)
);

create index if not exists idx_user_roles_user_id on public.user_roles(user_id);
